// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttconnector.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mqttconnector.implementation.CoreProxyImpl;
import java.io.File;
import java.io.FileInputStream;

public class FileToFileDocument extends CustomJavaAction<IMendixObject>
{
	private java.lang.String FileLocation;
	private java.lang.String FileDocumentEntity;

	public FileToFileDocument(IContext context, java.lang.String FileLocation, java.lang.String FileDocumentEntity)
	{
		super(context);
		this.FileLocation = FileLocation;
		this.FileDocumentEntity = FileDocumentEntity;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMendixObject mendixObject = Core.instantiate(getContext(), FileDocumentEntity);
		if (mendixObject.getMetaObject().getSuperName().equalsIgnoreCase("System.FileDocument") ||
				mendixObject.getMetaObject().getName().equalsIgnoreCase("System.FileDocument")){
			File file = new File(Core.getConfiguration().getResourcesPath() + File.separator+ FileLocation);
			Core.storeFileDocumentContent(getContext(),mendixObject, new FileInputStream(file));
			return mendixObject;
		}else throw new MendixRuntimeException("FileDocument entity is expected");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FileToFileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
