// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttconnector.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mqttconnector.implementation.PublishAction;

public class Publish extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __ConnectionDetail;
	private mqttconnector.proxies.ConnectionDetail ConnectionDetail;
	private java.lang.String Topic;
	private java.lang.String Payload;
	private mqttconnector.proxies.QoS QoS;
	private java.lang.Boolean Retained;

	public Publish(IContext context, IMendixObject ConnectionDetail, java.lang.String Topic, java.lang.String Payload, java.lang.String QoS, java.lang.Boolean Retained)
	{
		super(context);
		this.__ConnectionDetail = ConnectionDetail;
		this.Topic = Topic;
		this.Payload = Payload;
		this.QoS = QoS == null ? null : mqttconnector.proxies.QoS.valueOf(QoS);
		this.Retained = Retained;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.ConnectionDetail = this.__ConnectionDetail == null ? null : mqttconnector.proxies.ConnectionDetail.initialize(getContext(), __ConnectionDetail);

		// BEGIN USER CODE
		String clientIdPrefix = String.valueOf(Core.getConfiguration().getConstantValue("MqttConnector.ClientIdPrefix")) + Core.getConfiguration().getXASId();
		PublishAction publishAction = new PublishAction(clientIdPrefix, ConnectionDetail, Topic, Payload,QoS, Retained);
		return publishAction.execute();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Publish";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
